spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/store_db?createDatabaseIfNotExist=true
    username: user
    password: pass
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      database-platform: org.hibernate.dialect.MySQL8Dialect

strip:
  payment-method: strip
